config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('report/', include('reportapp.urls', namespace='report')),
    path('', RedirectView.as_view(url='report/'))
]

reportapp/urls.py
from django.urls import path

from reportapp import views
from reportapp.apps import ReportappConfig

app_name = ReportappConfig.name

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('', views.ContactCenterView.as_view(), name='home'),
    path('<int:pk>/detail_cc/', views.ContactCenterDetailView.as_view(), name='center_detail'),
    path('<int:pk>/group/', views.GroupView.as_view(), name='group'),
    path('<int:pk>/group_detail/', views.GroupDetailView.as_view(), name='group_detail'),
    path('<int:pk>/employee/', views.EmployeeView.as_view(), name='employee'),
    path('<str:name>/employee_detail/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('leaders/', views.RatingLeaders.as_view(), name='leaders'),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

reportapp/models.py
from django.db import models

from authapp.models import NULLABLE


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')
    deleted = models.BooleanField(default=False, verbose_name='Удалено')

    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()


class Area(BaseModel):
    area_name = models.CharField(max_length=100, verbose_name='Название площадки', unique=True)

    class Meta:
        verbose_name = 'Площадка'
        verbose_name_plural = 'Площадки'
        ordering = ['area_name']

    def __str__(self):
        return f'{self.area_name}'


class Group(BaseModel):
    group_name = models.CharField(max_length=100, verbose_name='Название группы', unique=True)

    class Meta:
        verbose_name = 'Группа опереторов'
        verbose_name_plural = 'Группы операторов'
        ordering = ['group_name']

    def __str__(self):
        return f'{self.group_name}'


class JobTitle(BaseModel):
    position = models.CharField(max_length=100, verbose_name='Должность', unique=True)
    calculated = models.BooleanField(default=True, verbose_name='Учитывается в расчете')

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'
        ordering = ['position']

    def __str__(self):
        return f'{self.position}'


class ReportData(BaseModel):
    date = models.DateField(auto_now=False, verbose_name='Дата', **NULLABLE)
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    group = models.ForeignKey(Group, on_delete=models.PROTECT, verbose_name='Группа')
    job = models.ForeignKey(JobTitle, on_delete=models.PROTECT, verbose_name='Должность')
    contact_center = models.ForeignKey(Area, on_delete=models.PROTECT, verbose_name='Площадка',
                                       related_name='contact_center')
    scheduled_time = models.FloatField(verbose_name='запланированное время')
    ready = models.FloatField(verbose_name='Ready')
    adherence = models.FloatField(verbose_name='Соблюдение расписания')
    sick_leave = models.FloatField(default=0, verbose_name='Больничные')
    absenteeism = models.FloatField(default=0, verbose_name='Отсутсвия')
    rating = models.FloatField(default=0, verbose_name='Рейтинг')

    class Meta:
        verbose_name = 'Данные отчета'
        verbose_name_plural = 'Данные отчета'
        ordering = ['date', 'contact_center', 'group', 'full_name', 'rating']

reportapp/views.py
import datetime
import logging
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.files.storage import FileSystemStorage
from django.db.models import Avg, Sum
from django.http import FileResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic import TemplateView

from config.settings import MEDIA_ROOT
from reportapp.models import ReportData, Area
from reportapp.services.report_services import contact_center_detail_service, group_detail_service, dates_parse, \
    employee_detail_service, rating_leaders
from reportapp.task import insert_data

logger = logging.getLogger(__name__)

FLAGS = {
    'CC main view': 'cc main view',
    'CC detail view': 'cc detail view',
    'Group main view': 'group main view',
    'Group detail view': 'group detail view',
    'Employee view': 'employee view',
    'Employee detail view': 'employee detail view'
}


def upload(request):
    if request.user.is_authenticated:
        if request.method == 'POST' and request.FILES and len(os.listdir(MEDIA_ROOT)) == 0:
            if request.FILES['upload']:
                upload_file = request.FILES['upload']
                if upload_file.name.endswith('.csv'):
                    fss = FileSystemStorage()
                    fss.save(upload_file.name, upload_file)
                    insert_data(upload_file.name)
                else:
                    messages.add_message(request, messages.WARNING,
                                         mark_safe("Неверный формат файла"))
        elif request.method == 'POST' and request.POST.get('delete') == 'Delete':
            for f in os.listdir(MEDIA_ROOT):
                os.remove(os.path.join(MEDIA_ROOT, f))
        with os.scandir(MEDIA_ROOT) as entries:
            file_url = ''
            for entry in entries:
                if entry.is_file():
                    file_url += entry.name
        return render(request, 'reportapp/upload.html', {'file_url': file_url})
    else:
        messages.add_message(request, messages.WARNING,
                             mark_safe("У Вас нет прав для просмотра данной страницы"))
        return redirect('report:home')


class ContactCenterView(TemplateView):
    template_name = 'reportapp/report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = ReportData.objects.order_by('-date').values('date').first()
        if date:
            date = date['date'].strftime('%Y-%m-%d')
        else:
            return context
        context['data'] = ReportData.objects.filter(date=date, job__calculated=True).values('contact_center',
                                                                                            'contact_center__area_name').annotate(
            scheduled_time_sum=Sum('scheduled_time'),
            ready_sum=Sum('ready'),
            rating_avg=Avg('rating'),
            adherence_avg=Avg('adherence'),
            sick_leave_sum=Sum('sick_leave'),
            absenteeism_sum=Sum('absenteeism'))
        context['flag'] = FLAGS['CC main view']
        context['cc_list'] = Area.objects.filter(deleted=False)
        return context


class ContactCenterDetailView(TemplateView):
    template_name = 'reportapp/report.html'

    def get_context_data(self, **kwargs):
        context = super(ContactCenterDetailView, self).get_context_data(**kwargs)
        date = ReportData.objects.order_by('-date').values('date').first()
        if date:
            date = date['date'].strftime('%Y-%m-%d')
        else:
            return context
        context['data'] = ReportData.objects.filter(contact_center=kwargs['pk'], date=date,
                                                    job__calculated=True).values(
            'date',
            'contact_center__area_name', 'contact_center').annotate(
            scheduled_time_sum=Sum('scheduled_time'),
            ready_sum=Sum('ready'),
            rating_avg=Avg('rating'),
            adherence_avg=Avg('adherence'),
            sick_leave_sum=Sum('sick_leave'),
            absenteeism_sum=Sum('absenteeism'))
        context['date'] = ReportData.objects.order_by('date').values('date').filter(
            contact_center=kwargs['pk']).distinct()
        context['contact_center_name'] = ReportData.objects.filter(contact_center=self.kwargs.get('pk')).values(
            'contact_center__area_name').first()
        context['flag'] = FLAGS['CC detail view']
        context['cc_list'] = Area.objects.filter(deleted=False)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        start, end = dates_parse(request)
        context['data'] = contact_center_detail_service(kwargs['pk'], start, end)
        context['date'] = ReportData.objects.order_by('date').values('date').filter(
            contact_center=self.kwargs.get('pk')).distinct()
        return self.render_to_response(context)


class GroupView(TemplateView):
    template_name = 'reportapp/report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = ReportData.objects.order_by('-date').values('date').first()
        if date:
            date = date['date'].strftime('%Y-%m-%d')
        else:
            return context
        context['data'] = ReportData.objects.filter(contact_center=self.kwargs.get('pk'),
                                                    date=date, job__calculated=True).values('group',
                                                                                            'group__group_name').annotate(
            scheduled_time_sum=Sum('scheduled_time'),
            ready_sum=Sum('ready'),
            rating_avg=Avg('rating'),
            adherence_avg=Avg('adherence'),
            sick_leave_sum=Sum('sick_leave'),
            absenteeism_sum=Sum('absenteeism')).order_by('group')
        context['flag'] = FLAGS['Group main view']
        return context


class GroupDetailView(TemplateView):
    template_name = 'reportapp/report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = ReportData.objects.order_by('-date').values('date').first()
        if date:
            date = date['date'].strftime('%Y-%m-%d')
        else:
            return context
        context['data'] = ReportData.objects.filter(group=self.kwargs.get('pk'),
                                                    date=date, job__calculated=True).values('date',
                                                                                            'group__group_name',
                                                                                            'group').annotate(
            scheduled_time_sum=Sum('scheduled_time'),
            ready_sum=Sum('ready'),
            rating_avg=Avg('rating'),
            adherence_avg=Avg('adherence'),
            sick_leave_sum=Sum('sick_leave'),
            absenteeism_sum=Sum('absenteeism'))
        context['date'] = ReportData.objects.order_by('date').values('date').filter(
            group=self.kwargs.get('pk')).distinct()
        context['flag'] = FLAGS['Group detail view']
        contact_center = ReportData.objects.filter(group=self.kwargs.get('pk')).first().contact_center
        context['group_list'] = ReportData.objects.order_by('group').values(
            'group', 'group__group_name').filter(contact_center=contact_center).distinct()
        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        start, end = dates_parse(request)
        context['data'] = group_detail_service(self.kwargs.get('pk'), start, end)
        context['date'] = ReportData.objects.order_by('date').values('date').filter(
            group=self.kwargs.get('pk')).distinct()
        context['gr_name'] = ReportData.objects.filter(group=self.kwargs.get('pk')).values('group__group_name').first()
        return self.render_to_response(context)


# def group_detail_view(request, pk):
#     start, end = data_parse(request)
#     print(start, end)
#     data = group_detail_service(pk, start, end)
#     date = ReportData.objects.order_by('date').values('date').filter(group=pk).distinct()
#     gr_name = ReportData.objects.filter(group=pk).values('group__group_name').first()
#     print(data)
#     return render(request, 'reportapp/report.html',
#                   {'data': data, 'date': date, 'gr_name': gr_name})
#
# def group_view(request, pk):
#     if request.method == 'POST':
#         try:
#             start_date_check = datetime.strptime(request.POST.get('start_date'), '%Y-%m-%d')
#             end_date_check = datetime.strptime(request.POST.get('end_date'), '%Y-%m-%d')
#             if end_date_check >= start_date_check:
#                 start_date = request.POST.get('start_date')
#                 end_date = request.POST.get('end_date')
#                 data = contact_center_detail_service(pk, start_date, end_date)
#             else:
#                 data = contact_center_detail_service(pk)
#                 messages.add_message(request, messages.WARNING,
#                                      mark_safe("Конечная дата не может быть меньше начальной"))
#         except ValueError:
#             data = contact_center_detail_service(pk)
#             messages.add_message(request, messages.WARNING, mark_safe("Выберите дату начала и дату конца периода"))
#     else:
#         data = contact_center_detail_service(pk)
#     date = ReportData.objects.order_by('date').values('date').filter(
#         contact_center=pk).distinct()
#     contact_center_name = ReportData.objects.filter(contact_center=pk).values('contact_center__area_name').first()
#     print(data)

reportapp/templates/reportapp/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https:////cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
<header class="navbar sticky-top flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-5" href="{% url 'report:home' %}">МегаФон</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            {% if user.is_authenticated %}
                <a class="nav-link px-3 fs-5" href="{% url 'authapp:logout' %}">Выйти</a>
            {% else %}
                <a class="nav-link px-3 fs-5" href="{% url 'authapp:login' %}">Войти</a>
            {% endif %}
        </div>
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3 sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-warning text-center fs-6" aria-current="page"
                           href="{% url 'report:home' %}">
                            ВЕРНУТЬСЯ НА ГЛАВНУЮ
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-success text-center fs-6" aria-current="page"
                           href="{% url 'report:leaders' %}">
                            Лидеры рейтинга
                        </a>
                    </li>
                    <li class="nav-item">
                        {% if flag == 'cc main view' or flag == 'cc detail view' %}
                            <li class="my-2">
                                <button class="btn d-inline-flex align-items-center collapsed border-0"
                                        data-bs-toggle="collapse" aria-expanded="false"
                                        data-bs-target="#contents-collapse"
                                        aria-controls="contents-collapse">Площадки
                                </button>
                                <ul class="list-unstyled ps-3" id="contents-collapse">
                                    {% for item in cc_list %}
                                        {% if item.area_name %}
                                            <li><a class="nav-link"
                                                   href="{% url 'report:center_detail' pk=item.pk %}">{{ item.area_name }}</a>
                                            </li>
                                        {% else %}
                                            <li></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% elif flag == 'group main view' or flag == 'group detail view' %}
                            <li class="my-2">
                                <button class="btn d-inline-flex align-items-center collapsed border-0"
                                        data-bs-toggle="collapse" aria-expanded="false"
                                        data-bs-target="#contents-collapse"
                                        aria-controls="contents-collapse">Группы
                                </button>
                                <ul class="list-unstyled ps-3" id="contents-collapse">
                                    {% if group_list %}
                                        {% for group in group_list %}
                                            <li><a class="nav-link"
                                                   href="{% url 'report:group_detail' pk=group.group %}">{{ group.group__group_name }}</a>
                                            </li>
                                        {% endfor %}
                                    {% else %}
                                        {% for item in data %}
                                            {% if item.group__group_name %}
                                                <li><a class="nav-link"
                                                       href="{% url 'report:group_detail' pk=item.group %}">{{ item.group__group_name }}</a>
                                                </li>
                                            {% else %}
                                                <li></li>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                        </li>
                                    {% endif %}
                        {% endif %}

                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">#}
                    {#                            <span data-feather="shopping-cart" class="align-text-bottom"></span>#}
                    {#                            Products#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">#}
                    {#                            <span data-feather="users" class="align-text-bottom"></span>#}
                    {#                            Customers#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">#}
                    {#                            <span data-feather="bar-chart-2" class="align-text-bottom"></span>#}
                    {#                            Reports#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">#}
                    {#                            <span data-feather="layers" class="align-text-bottom"></span>#}
                    {#                            Integrations#}
                    {#                        </a>#}
                    {#                    </li>#}
                </ul>
                {% if user.is_authenticated %}
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
                        <span>Служебный раздел</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'report:upload' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Загрузка данных
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'report:log_view' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Логи
                            </a>
                        </li>
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="#">#}
{#                                <span data-feather="file-text" class="align-text-bottom"></span>#}
{#                                Social engagement#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="#">#}
{#                                <span data-feather="file-text" class="align-text-bottom"></span>#}
{#                                Year-end sale#}
{#                            </a>#}
{#                        </li>#}
                    </ul>
                {% endif %}
            </div>
        </nav>
    </div>
</div>


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

    {% block content %}
    {% endblock %}

</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script>
    {% for message in messages %}
        console.log("{{ message.tags }}")
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.{{ message.tags }}("{{ message }}");
    {% endfor %}
</script>
</body>
</html>

reportapp/templates/reportapp/home.html
{% extends 'reportapp/base.html' %}

reportapp/templates/reportapp/leaders.html
{% extends 'reportapp/base.html' %}
{% load extras %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="container-fluid">

            {% if date %}
                <form method="post" action="">
                    <div class="row">
                        {% csrf_token %}
                        <div class="col-2">
                            <select class="form-select" aria-label="Default select example" name="leaders_date">
                                <option selected>Выберите дату</option>
                                {% for d in date %}
                                    <option name="start_date"
                                            value="{{ d.date|date:"Y-m-d" }}">{{ d.date|date:"M Y" }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-1">
                            <button type="submit" class="btn btn-success">Выбрать</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

    <div class="container justify-content-center text-center fs-3 mt-2">
        Лидеры рейтинга за {{ date_label|date:"F Y" }}
    </div>
    <div class="container justify-content-center mt-2">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Дата</th>
                <th scope="col">Сотрудник</th>
                <th scope="col">Рейтинг</th>
            </tr>
            </thead>
            {% for d in data %}
                <tr>
                    <td class="fs-6">{{ d.date|date:"M Y" }}</td>
                    <td>{{ d.full_name }}</td>
                    <td>{{ d.rating|percent }}%</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

reportapp/templates/reportapp/log_view.html
{% extends 'reportapp/base.html' %}
{% block content %}
    <div class="row justify-content-end my-2">
        <div class="col-sm-4 col-lg-2">
            <a href="{% url 'report:log_download' %}" class="btn btn-primary btn-block" role="button">Скачать</a>
        </div>
    </div>
    <p>
        <div class="text-center text-muted">
            <small>Last lines of log file</small>
        </div>
        <pre>{{ log }}</pre>
    </p>
{% endblock content %}

reportapp/templates/reportapp/upload.html
{% extends 'reportapp/base.html' %}
{% block content %}

    {% if file_url %}
        <h2 class="my-4">Загруженные файлы</h2>
        <div class="col-lg-3 col-md-6 col-sm-6 pb-4">
            <p>Uploaded to: {{ file_url }}</p>
            <a class="btn btn-dark my-4" href="{% url 'report:home' %}">Вернуться на главную</a>
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Введи Delete для удаления всех
                        файлов</label>
                    <input type="text" class="form-control" name="delete">
                </div>
                <button class="btn btn-danger my-1" type="submit">Удалить файл</button>
            </form>
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-5">
                    <h2 class="my-4">Выбери файл для загрузки</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-1">
                            <input class="form-control" type="file" name="upload" id="formFile">
                        </div>
                        <br>
                        <button class="btn btn-success" type="submit">Загрузить</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}